/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/GetModuleTwist.srv */
#ifndef MODULE_CONTROLLER_SERVICE_GETMODULETWIST_H
#define MODULE_CONTROLLER_SERVICE_GETMODULETWIST_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct GetModuleTwistRequest_ : public ros::Message
{
  typedef GetModuleTwistRequest_<ContainerAllocator> Type;

  GetModuleTwistRequest_()
  : ID(0)
  {
  }

  GetModuleTwistRequest_(const ContainerAllocator& _alloc)
  : ID(0)
  {
  }

  typedef int8_t _ID_type;
  int8_t ID;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleTwistRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0cb5143ed23a5de01874507c8711c4d5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "9ef85376904fa5a329707b43ba3623a5"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 ID\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ID);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleTwistRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleTwistRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleTwistRequest
typedef  ::module_controller::GetModuleTwistRequest_<std::allocator<void> > GetModuleTwistRequest;

typedef boost::shared_ptr< ::module_controller::GetModuleTwistRequest> GetModuleTwistRequestPtr;
typedef boost::shared_ptr< ::module_controller::GetModuleTwistRequest const> GetModuleTwistRequestConstPtr;


template <class ContainerAllocator>
struct GetModuleTwistResponse_ : public ros::Message
{
  typedef GetModuleTwistResponse_<ContainerAllocator> Type;

  GetModuleTwistResponse_()
  : Twist(0.0)
  {
  }

  GetModuleTwistResponse_(const ContainerAllocator& _alloc)
  : Twist(0.0)
  {
  }

  typedef float _Twist_type;
  float Twist;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleTwistResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8f7813e47b9e5c0b6adb249c3d4066cb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "9ef85376904fa5a329707b43ba3623a5"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 Twist\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Twist);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Twist);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Twist);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleTwistResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleTwistResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleTwistResponse
typedef  ::module_controller::GetModuleTwistResponse_<std::allocator<void> > GetModuleTwistResponse;

typedef boost::shared_ptr< ::module_controller::GetModuleTwistResponse> GetModuleTwistResponsePtr;
typedef boost::shared_ptr< ::module_controller::GetModuleTwistResponse const> GetModuleTwistResponseConstPtr;

struct GetModuleTwist
{

typedef GetModuleTwistRequest Request;
typedef GetModuleTwistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetModuleTwist
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleTwistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const  ::module_controller::GetModuleTwistRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0cb5143ed23a5de0ULL;
  static const uint64_t static_value2 = 0x1874507c8711c4d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleTwistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTwistRequest";
  }

  static const char* value(const  ::module_controller::GetModuleTwistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleTwistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 ID\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleTwistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleTwistRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleTwistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8f7813e47b9e5c0b6adb249c3d4066cb";
  }

  static const char* value(const  ::module_controller::GetModuleTwistResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8f7813e47b9e5c0bULL;
  static const uint64_t static_value2 = 0x6adb249c3d4066cbULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleTwistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTwistResponse";
  }

  static const char* value(const  ::module_controller::GetModuleTwistResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleTwistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 Twist\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleTwistResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleTwistResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleTwistRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ID);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleTwistRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleTwistResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Twist);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleTwistResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::GetModuleTwist> {
  static const char* value() 
  {
    return "9ef85376904fa5a329707b43ba3623a5";
  }

  static const char* value(const module_controller::GetModuleTwist&) { return value(); } 
};

template<>
struct DataType<module_controller::GetModuleTwist> {
  static const char* value() 
  {
    return "module_controller/GetModuleTwist";
  }

  static const char* value(const module_controller::GetModuleTwist&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleTwistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9ef85376904fa5a329707b43ba3623a5";
  }

  static const char* value(const module_controller::GetModuleTwistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleTwistRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTwist";
  }

  static const char* value(const module_controller::GetModuleTwistRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleTwistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9ef85376904fa5a329707b43ba3623a5";
  }

  static const char* value(const module_controller::GetModuleTwistResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleTwistResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTwist";
  }

  static const char* value(const module_controller::GetModuleTwistResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_GETMODULETWIST_H

