/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/GetModuleTotal.srv */
#ifndef MODULE_CONTROLLER_SERVICE_GETMODULETOTAL_H
#define MODULE_CONTROLLER_SERVICE_GETMODULETOTAL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct GetModuleTotalRequest_ : public ros::Message
{
  typedef GetModuleTotalRequest_<ContainerAllocator> Type;

  GetModuleTotalRequest_()
  : Nothing(0)
  {
  }

  GetModuleTotalRequest_(const ContainerAllocator& _alloc)
  : Nothing(0)
  {
  }

  typedef int8_t _Nothing_type;
  int8_t Nothing;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleTotalRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "614b939b5fa1fbf0c2d50eee578a4e28"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "443eae3a81f8e9931eb80c6e96bb1875"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Nothing\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Nothing);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Nothing);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Nothing);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleTotalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleTotalRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleTotalRequest
typedef  ::module_controller::GetModuleTotalRequest_<std::allocator<void> > GetModuleTotalRequest;

typedef boost::shared_ptr< ::module_controller::GetModuleTotalRequest> GetModuleTotalRequestPtr;
typedef boost::shared_ptr< ::module_controller::GetModuleTotalRequest const> GetModuleTotalRequestConstPtr;


template <class ContainerAllocator>
struct GetModuleTotalResponse_ : public ros::Message
{
  typedef GetModuleTotalResponse_<ContainerAllocator> Type;

  GetModuleTotalResponse_()
  : Total(0)
  {
  }

  GetModuleTotalResponse_(const ContainerAllocator& _alloc)
  : Total(0)
  {
  }

  typedef int8_t _Total_type;
  int8_t Total;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleTotalResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4ff53f29d37440102cc007ea816b9b8e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "443eae3a81f8e9931eb80c6e96bb1875"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Total\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Total);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Total);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Total);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleTotalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleTotalResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleTotalResponse
typedef  ::module_controller::GetModuleTotalResponse_<std::allocator<void> > GetModuleTotalResponse;

typedef boost::shared_ptr< ::module_controller::GetModuleTotalResponse> GetModuleTotalResponsePtr;
typedef boost::shared_ptr< ::module_controller::GetModuleTotalResponse const> GetModuleTotalResponseConstPtr;

struct GetModuleTotal
{

typedef GetModuleTotalRequest Request;
typedef GetModuleTotalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetModuleTotal
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleTotalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "614b939b5fa1fbf0c2d50eee578a4e28";
  }

  static const char* value(const  ::module_controller::GetModuleTotalRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x614b939b5fa1fbf0ULL;
  static const uint64_t static_value2 = 0xc2d50eee578a4e28ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleTotalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTotalRequest";
  }

  static const char* value(const  ::module_controller::GetModuleTotalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleTotalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Nothing\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleTotalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleTotalRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleTotalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4ff53f29d37440102cc007ea816b9b8e";
  }

  static const char* value(const  ::module_controller::GetModuleTotalResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4ff53f29d3744010ULL;
  static const uint64_t static_value2 = 0x2cc007ea816b9b8eULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleTotalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTotalResponse";
  }

  static const char* value(const  ::module_controller::GetModuleTotalResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleTotalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Total\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleTotalResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleTotalResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleTotalRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Nothing);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleTotalRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleTotalResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Total);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleTotalResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::GetModuleTotal> {
  static const char* value() 
  {
    return "443eae3a81f8e9931eb80c6e96bb1875";
  }

  static const char* value(const module_controller::GetModuleTotal&) { return value(); } 
};

template<>
struct DataType<module_controller::GetModuleTotal> {
  static const char* value() 
  {
    return "module_controller/GetModuleTotal";
  }

  static const char* value(const module_controller::GetModuleTotal&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleTotalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "443eae3a81f8e9931eb80c6e96bb1875";
  }

  static const char* value(const module_controller::GetModuleTotalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleTotalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTotal";
  }

  static const char* value(const module_controller::GetModuleTotalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleTotalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "443eae3a81f8e9931eb80c6e96bb1875";
  }

  static const char* value(const module_controller::GetModuleTotalResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleTotalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleTotal";
  }

  static const char* value(const module_controller::GetModuleTotalResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_GETMODULETOTAL_H

