/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/GetModuleLengths.srv */
#ifndef MODULE_CONTROLLER_SERVICE_GETMODULELENGTHS_H
#define MODULE_CONTROLLER_SERVICE_GETMODULELENGTHS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct GetModuleLengthsRequest_ : public ros::Message
{
  typedef GetModuleLengthsRequest_<ContainerAllocator> Type;

  GetModuleLengthsRequest_()
  : ID(0)
  {
  }

  GetModuleLengthsRequest_(const ContainerAllocator& _alloc)
  : ID(0)
  {
  }

  typedef int8_t _ID_type;
  int8_t ID;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleLengthsRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0cb5143ed23a5de01874507c8711c4d5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4dedf9a1defa9906f28f1326090fd468"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 ID\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ID);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleLengthsRequest
typedef  ::module_controller::GetModuleLengthsRequest_<std::allocator<void> > GetModuleLengthsRequest;

typedef boost::shared_ptr< ::module_controller::GetModuleLengthsRequest> GetModuleLengthsRequestPtr;
typedef boost::shared_ptr< ::module_controller::GetModuleLengthsRequest const> GetModuleLengthsRequestConstPtr;


template <class ContainerAllocator>
struct GetModuleLengthsResponse_ : public ros::Message
{
  typedef GetModuleLengthsResponse_<ContainerAllocator> Type;

  GetModuleLengthsResponse_()
  : Upstream(0.0)
  , Downstream(0.0)
  {
  }

  GetModuleLengthsResponse_(const ContainerAllocator& _alloc)
  : Upstream(0.0)
  , Downstream(0.0)
  {
  }

  typedef float _Upstream_type;
  float Upstream;

  typedef float _Downstream_type;
  float Downstream;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleLengthsResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0a45ac63b3ef4c7791b03e2498545874"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4dedf9a1defa9906f28f1326090fd468"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 Upstream\n\
float32 Downstream\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Upstream);
    ros::serialization::serialize(stream, Downstream);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Upstream);
    ros::serialization::deserialize(stream, Downstream);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Upstream);
    size += ros::serialization::serializationLength(Downstream);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleLengthsResponse
typedef  ::module_controller::GetModuleLengthsResponse_<std::allocator<void> > GetModuleLengthsResponse;

typedef boost::shared_ptr< ::module_controller::GetModuleLengthsResponse> GetModuleLengthsResponsePtr;
typedef boost::shared_ptr< ::module_controller::GetModuleLengthsResponse const> GetModuleLengthsResponseConstPtr;

struct GetModuleLengths
{

typedef GetModuleLengthsRequest Request;
typedef GetModuleLengthsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetModuleLengths
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const  ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0cb5143ed23a5de0ULL;
  static const uint64_t static_value2 = 0x1874507c8711c4d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleLengthsRequest";
  }

  static const char* value(const  ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 ID\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0a45ac63b3ef4c7791b03e2498545874";
  }

  static const char* value(const  ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0a45ac63b3ef4c77ULL;
  static const uint64_t static_value2 = 0x91b03e2498545874ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleLengthsResponse";
  }

  static const char* value(const  ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 Upstream\n\
float32 Downstream\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleLengthsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ID);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleLengthsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleLengthsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Upstream);
    stream.next(m.Downstream);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleLengthsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::GetModuleLengths> {
  static const char* value() 
  {
    return "4dedf9a1defa9906f28f1326090fd468";
  }

  static const char* value(const module_controller::GetModuleLengths&) { return value(); } 
};

template<>
struct DataType<module_controller::GetModuleLengths> {
  static const char* value() 
  {
    return "module_controller/GetModuleLengths";
  }

  static const char* value(const module_controller::GetModuleLengths&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleLengthsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4dedf9a1defa9906f28f1326090fd468";
  }

  static const char* value(const module_controller::GetModuleLengthsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleLengthsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleLengths";
  }

  static const char* value(const module_controller::GetModuleLengthsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleLengthsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4dedf9a1defa9906f28f1326090fd468";
  }

  static const char* value(const module_controller::GetModuleLengthsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleLengthsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleLengths";
  }

  static const char* value(const module_controller::GetModuleLengthsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_GETMODULELENGTHS_H

