/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/GetModuleOffset.srv */
#ifndef MODULE_CONTROLLER_SERVICE_GETMODULEOFFSET_H
#define MODULE_CONTROLLER_SERVICE_GETMODULEOFFSET_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct GetModuleOffsetRequest_ : public ros::Message
{
  typedef GetModuleOffsetRequest_<ContainerAllocator> Type;

  GetModuleOffsetRequest_()
  : ID(0)
  {
  }

  GetModuleOffsetRequest_(const ContainerAllocator& _alloc)
  : ID(0)
  {
  }

  typedef int8_t _ID_type;
  int8_t ID;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleOffsetRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0cb5143ed23a5de01874507c8711c4d5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d0507e8dc19c9273ee2f093c09374bee"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 ID\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ID);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleOffsetRequest
typedef  ::module_controller::GetModuleOffsetRequest_<std::allocator<void> > GetModuleOffsetRequest;

typedef boost::shared_ptr< ::module_controller::GetModuleOffsetRequest> GetModuleOffsetRequestPtr;
typedef boost::shared_ptr< ::module_controller::GetModuleOffsetRequest const> GetModuleOffsetRequestConstPtr;


template <class ContainerAllocator>
struct GetModuleOffsetResponse_ : public ros::Message
{
  typedef GetModuleOffsetResponse_<ContainerAllocator> Type;

  GetModuleOffsetResponse_()
  : Offset(0)
  {
  }

  GetModuleOffsetResponse_(const ContainerAllocator& _alloc)
  : Offset(0)
  {
  }

  typedef int16_t _Offset_type;
  int16_t Offset;


private:
  static const char* __s_getDataType_() { return "module_controller/GetModuleOffsetResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "bd318d9714b1ebe5501ec07929c17672"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d0507e8dc19c9273ee2f093c09374bee"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 Offset\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Offset);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Offset);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Offset);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetModuleOffsetResponse
typedef  ::module_controller::GetModuleOffsetResponse_<std::allocator<void> > GetModuleOffsetResponse;

typedef boost::shared_ptr< ::module_controller::GetModuleOffsetResponse> GetModuleOffsetResponsePtr;
typedef boost::shared_ptr< ::module_controller::GetModuleOffsetResponse const> GetModuleOffsetResponseConstPtr;

struct GetModuleOffset
{

typedef GetModuleOffsetRequest Request;
typedef GetModuleOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetModuleOffset
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const  ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0cb5143ed23a5de0ULL;
  static const uint64_t static_value2 = 0x1874507c8711c4d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleOffsetRequest";
  }

  static const char* value(const  ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 ID\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bd318d9714b1ebe5501ec07929c17672";
  }

  static const char* value(const  ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbd318d9714b1ebe5ULL;
  static const uint64_t static_value2 = 0x501ec07929c17672ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleOffsetResponse";
  }

  static const char* value(const  ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 Offset\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleOffsetRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ID);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleOffsetRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetModuleOffsetResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Offset);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetModuleOffsetResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::GetModuleOffset> {
  static const char* value() 
  {
    return "d0507e8dc19c9273ee2f093c09374bee";
  }

  static const char* value(const module_controller::GetModuleOffset&) { return value(); } 
};

template<>
struct DataType<module_controller::GetModuleOffset> {
  static const char* value() 
  {
    return "module_controller/GetModuleOffset";
  }

  static const char* value(const module_controller::GetModuleOffset&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleOffsetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d0507e8dc19c9273ee2f093c09374bee";
  }

  static const char* value(const module_controller::GetModuleOffsetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleOffsetRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleOffset";
  }

  static const char* value(const module_controller::GetModuleOffsetRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetModuleOffsetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d0507e8dc19c9273ee2f093c09374bee";
  }

  static const char* value(const module_controller::GetModuleOffsetResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetModuleOffsetResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetModuleOffset";
  }

  static const char* value(const module_controller::GetModuleOffsetResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_GETMODULEOFFSET_H

