/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/GetServoSpeed.srv */
#ifndef MODULE_CONTROLLER_SERVICE_GETSERVOSPEED_H
#define MODULE_CONTROLLER_SERVICE_GETSERVOSPEED_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct GetServoSpeedRequest_ : public ros::Message
{
  typedef GetServoSpeedRequest_<ContainerAllocator> Type;

  GetServoSpeedRequest_()
  : ID(0)
  {
  }

  GetServoSpeedRequest_(const ContainerAllocator& _alloc)
  : ID(0)
  {
  }

  typedef int8_t _ID_type;
  int8_t ID;


private:
  static const char* __s_getDataType_() { return "module_controller/GetServoSpeedRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0cb5143ed23a5de01874507c8711c4d5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "86b923d1c96b0ad1a92b39bae3ff7fad"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 ID\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ID);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ID);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetServoSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetServoSpeedRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetServoSpeedRequest
typedef  ::module_controller::GetServoSpeedRequest_<std::allocator<void> > GetServoSpeedRequest;

typedef boost::shared_ptr< ::module_controller::GetServoSpeedRequest> GetServoSpeedRequestPtr;
typedef boost::shared_ptr< ::module_controller::GetServoSpeedRequest const> GetServoSpeedRequestConstPtr;


template <class ContainerAllocator>
struct GetServoSpeedResponse_ : public ros::Message
{
  typedef GetServoSpeedResponse_<ContainerAllocator> Type;

  GetServoSpeedResponse_()
  : Speed(0)
  {
  }

  GetServoSpeedResponse_(const ContainerAllocator& _alloc)
  : Speed(0)
  {
  }

  typedef int8_t _Speed_type;
  int8_t Speed;


private:
  static const char* __s_getDataType_() { return "module_controller/GetServoSpeedResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "50d227584c708750adc2009e36b6ba4f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "86b923d1c96b0ad1a92b39bae3ff7fad"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Speed\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Speed);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::GetServoSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::GetServoSpeedResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetServoSpeedResponse
typedef  ::module_controller::GetServoSpeedResponse_<std::allocator<void> > GetServoSpeedResponse;

typedef boost::shared_ptr< ::module_controller::GetServoSpeedResponse> GetServoSpeedResponsePtr;
typedef boost::shared_ptr< ::module_controller::GetServoSpeedResponse const> GetServoSpeedResponseConstPtr;

struct GetServoSpeed
{

typedef GetServoSpeedRequest Request;
typedef GetServoSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetServoSpeed
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0cb5143ed23a5de01874507c8711c4d5";
  }

  static const char* value(const  ::module_controller::GetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0cb5143ed23a5de0ULL;
  static const uint64_t static_value2 = 0x1874507c8711c4d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetServoSpeedRequest";
  }

  static const char* value(const  ::module_controller::GetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 ID\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetServoSpeedRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::GetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "50d227584c708750adc2009e36b6ba4f";
  }

  static const char* value(const  ::module_controller::GetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x50d227584c708750ULL;
  static const uint64_t static_value2 = 0xadc2009e36b6ba4fULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::GetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetServoSpeedResponse";
  }

  static const char* value(const  ::module_controller::GetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::GetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Speed\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::GetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::GetServoSpeedResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetServoSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ID);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetServoSpeedRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::GetServoSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetServoSpeedResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::GetServoSpeed> {
  static const char* value() 
  {
    return "86b923d1c96b0ad1a92b39bae3ff7fad";
  }

  static const char* value(const module_controller::GetServoSpeed&) { return value(); } 
};

template<>
struct DataType<module_controller::GetServoSpeed> {
  static const char* value() 
  {
    return "module_controller/GetServoSpeed";
  }

  static const char* value(const module_controller::GetServoSpeed&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "86b923d1c96b0ad1a92b39bae3ff7fad";
  }

  static const char* value(const module_controller::GetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetServoSpeed";
  }

  static const char* value(const module_controller::GetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::GetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "86b923d1c96b0ad1a92b39bae3ff7fad";
  }

  static const char* value(const module_controller::GetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::GetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/GetServoSpeed";
  }

  static const char* value(const module_controller::GetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_GETSERVOSPEED_H

