/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/ResetRobot.srv */
#ifndef MODULE_CONTROLLER_SERVICE_RESETROBOT_H
#define MODULE_CONTROLLER_SERVICE_RESETROBOT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct ResetRobotRequest_ : public ros::Message
{
  typedef ResetRobotRequest_<ContainerAllocator> Type;

  ResetRobotRequest_()
  : Nothing(0)
  {
  }

  ResetRobotRequest_(const ContainerAllocator& _alloc)
  : Nothing(0)
  {
  }

  typedef int8_t _Nothing_type;
  int8_t Nothing;


private:
  static const char* __s_getDataType_() { return "module_controller/ResetRobotRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "614b939b5fa1fbf0c2d50eee578a4e28"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4a1954151a0c2d771839ed336f9b5647"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Nothing\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Nothing);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Nothing);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Nothing);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::ResetRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::ResetRobotRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct ResetRobotRequest
typedef  ::module_controller::ResetRobotRequest_<std::allocator<void> > ResetRobotRequest;

typedef boost::shared_ptr< ::module_controller::ResetRobotRequest> ResetRobotRequestPtr;
typedef boost::shared_ptr< ::module_controller::ResetRobotRequest const> ResetRobotRequestConstPtr;


template <class ContainerAllocator>
struct ResetRobotResponse_ : public ros::Message
{
  typedef ResetRobotResponse_<ContainerAllocator> Type;

  ResetRobotResponse_()
  : Success(0)
  {
  }

  ResetRobotResponse_(const ContainerAllocator& _alloc)
  : Success(0)
  {
  }

  typedef int8_t _Success_type;
  int8_t Success;


private:
  static const char* __s_getDataType_() { return "module_controller/ResetRobotResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1a8c06f1b4403f4bedd5ebdeca1af0dd"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "4a1954151a0c2d771839ed336f9b5647"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Success);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::ResetRobotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::ResetRobotResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct ResetRobotResponse
typedef  ::module_controller::ResetRobotResponse_<std::allocator<void> > ResetRobotResponse;

typedef boost::shared_ptr< ::module_controller::ResetRobotResponse> ResetRobotResponsePtr;
typedef boost::shared_ptr< ::module_controller::ResetRobotResponse const> ResetRobotResponseConstPtr;

struct ResetRobot
{

typedef ResetRobotRequest Request;
typedef ResetRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ResetRobot
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::ResetRobotRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "614b939b5fa1fbf0c2d50eee578a4e28";
  }

  static const char* value(const  ::module_controller::ResetRobotRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x614b939b5fa1fbf0ULL;
  static const uint64_t static_value2 = 0xc2d50eee578a4e28ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::ResetRobotRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/ResetRobotRequest";
  }

  static const char* value(const  ::module_controller::ResetRobotRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::ResetRobotRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Nothing\n\
\n\
";
  }

  static const char* value(const  ::module_controller::ResetRobotRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::ResetRobotRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::ResetRobotResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a8c06f1b4403f4bedd5ebdeca1af0dd";
  }

  static const char* value(const  ::module_controller::ResetRobotResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1a8c06f1b4403f4bULL;
  static const uint64_t static_value2 = 0xedd5ebdeca1af0ddULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::ResetRobotResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/ResetRobotResponse";
  }

  static const char* value(const  ::module_controller::ResetRobotResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::ResetRobotResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Success\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::ResetRobotResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::ResetRobotResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::ResetRobotRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Nothing);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ResetRobotRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::ResetRobotResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ResetRobotResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::ResetRobot> {
  static const char* value() 
  {
    return "4a1954151a0c2d771839ed336f9b5647";
  }

  static const char* value(const module_controller::ResetRobot&) { return value(); } 
};

template<>
struct DataType<module_controller::ResetRobot> {
  static const char* value() 
  {
    return "module_controller/ResetRobot";
  }

  static const char* value(const module_controller::ResetRobot&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::ResetRobotRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a1954151a0c2d771839ed336f9b5647";
  }

  static const char* value(const module_controller::ResetRobotRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::ResetRobotRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/ResetRobot";
  }

  static const char* value(const module_controller::ResetRobotRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::ResetRobotResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a1954151a0c2d771839ed336f9b5647";
  }

  static const char* value(const module_controller::ResetRobotResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::ResetRobotResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/ResetRobot";
  }

  static const char* value(const module_controller::ResetRobotResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_RESETROBOT_H

