/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/SetServoSpeed.srv */
#ifndef MODULE_CONTROLLER_SERVICE_SETSERVOSPEED_H
#define MODULE_CONTROLLER_SERVICE_SETSERVOSPEED_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct SetServoSpeedRequest_ : public ros::Message
{
  typedef SetServoSpeedRequest_<ContainerAllocator> Type;

  SetServoSpeedRequest_()
  : ID(0)
  , Speed(0)
  {
  }

  SetServoSpeedRequest_(const ContainerAllocator& _alloc)
  : ID(0)
  , Speed(0)
  {
  }

  typedef int8_t _ID_type;
  int8_t ID;

  typedef int8_t _Speed_type;
  int8_t Speed;


private:
  static const char* __s_getDataType_() { return "module_controller/SetServoSpeedRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "de8cd72f9f86441d3b236f94ac99eeee"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "a5cb71dde39d64eb1c071c1bee620dba"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 ID\n\
int8 Speed\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ID);
    ros::serialization::serialize(stream, Speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ID);
    ros::serialization::deserialize(stream, Speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ID);
    size += ros::serialization::serializationLength(Speed);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::SetServoSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::SetServoSpeedRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SetServoSpeedRequest
typedef  ::module_controller::SetServoSpeedRequest_<std::allocator<void> > SetServoSpeedRequest;

typedef boost::shared_ptr< ::module_controller::SetServoSpeedRequest> SetServoSpeedRequestPtr;
typedef boost::shared_ptr< ::module_controller::SetServoSpeedRequest const> SetServoSpeedRequestConstPtr;


template <class ContainerAllocator>
struct SetServoSpeedResponse_ : public ros::Message
{
  typedef SetServoSpeedResponse_<ContainerAllocator> Type;

  SetServoSpeedResponse_()
  : Success(0)
  {
  }

  SetServoSpeedResponse_(const ContainerAllocator& _alloc)
  : Success(0)
  {
  }

  typedef int8_t _Success_type;
  int8_t Success;


private:
  static const char* __s_getDataType_() { return "module_controller/SetServoSpeedResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1a8c06f1b4403f4bedd5ebdeca1af0dd"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "a5cb71dde39d64eb1c071c1bee620dba"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Success);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::SetServoSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::SetServoSpeedResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SetServoSpeedResponse
typedef  ::module_controller::SetServoSpeedResponse_<std::allocator<void> > SetServoSpeedResponse;

typedef boost::shared_ptr< ::module_controller::SetServoSpeedResponse> SetServoSpeedResponsePtr;
typedef boost::shared_ptr< ::module_controller::SetServoSpeedResponse const> SetServoSpeedResponseConstPtr;

struct SetServoSpeed
{

typedef SetServoSpeedRequest Request;
typedef SetServoSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetServoSpeed
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::SetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "de8cd72f9f86441d3b236f94ac99eeee";
  }

  static const char* value(const  ::module_controller::SetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xde8cd72f9f86441dULL;
  static const uint64_t static_value2 = 0x3b236f94ac99eeeeULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::SetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoSpeedRequest";
  }

  static const char* value(const  ::module_controller::SetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::SetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 ID\n\
int8 Speed\n\
\n\
";
  }

  static const char* value(const  ::module_controller::SetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::SetServoSpeedRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::SetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a8c06f1b4403f4bedd5ebdeca1af0dd";
  }

  static const char* value(const  ::module_controller::SetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1a8c06f1b4403f4bULL;
  static const uint64_t static_value2 = 0xedd5ebdeca1af0ddULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::SetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoSpeedResponse";
  }

  static const char* value(const  ::module_controller::SetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::SetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Success\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::SetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::SetServoSpeedResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::SetServoSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ID);
    stream.next(m.Speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetServoSpeedRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::SetServoSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetServoSpeedResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::SetServoSpeed> {
  static const char* value() 
  {
    return "a5cb71dde39d64eb1c071c1bee620dba";
  }

  static const char* value(const module_controller::SetServoSpeed&) { return value(); } 
};

template<>
struct DataType<module_controller::SetServoSpeed> {
  static const char* value() 
  {
    return "module_controller/SetServoSpeed";
  }

  static const char* value(const module_controller::SetServoSpeed&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::SetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a5cb71dde39d64eb1c071c1bee620dba";
  }

  static const char* value(const module_controller::SetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::SetServoSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoSpeed";
  }

  static const char* value(const module_controller::SetServoSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::SetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a5cb71dde39d64eb1c071c1bee620dba";
  }

  static const char* value(const module_controller::SetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::SetServoSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoSpeed";
  }

  static const char* value(const module_controller::SetServoSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_SETSERVOSPEED_H

