/* Auto-generated by genmsg_cpp for file /home/jason/ros_packages/module_controller/srv/SetServoAngle.srv */
#ifndef MODULE_CONTROLLER_SERVICE_SETSERVOANGLE_H
#define MODULE_CONTROLLER_SERVICE_SETSERVOANGLE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace module_controller
{
template <class ContainerAllocator>
struct SetServoAngleRequest_ : public ros::Message
{
  typedef SetServoAngleRequest_<ContainerAllocator> Type;

  SetServoAngleRequest_()
  : ID(0)
  , Angle(0.0)
  {
  }

  SetServoAngleRequest_(const ContainerAllocator& _alloc)
  : ID(0)
  , Angle(0.0)
  {
  }

  typedef int8_t _ID_type;
  int8_t ID;

  typedef float _Angle_type;
  float Angle;


private:
  static const char* __s_getDataType_() { return "module_controller/SetServoAngleRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5c52a171b7b8052392cf8b6496ff8559"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c5ba78eaaf56070109b47d88ff7a70ae"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 ID\n\
float32 Angle\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, ID);
    ros::serialization::serialize(stream, Angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, ID);
    ros::serialization::deserialize(stream, Angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(ID);
    size += ros::serialization::serializationLength(Angle);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::SetServoAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::SetServoAngleRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SetServoAngleRequest
typedef  ::module_controller::SetServoAngleRequest_<std::allocator<void> > SetServoAngleRequest;

typedef boost::shared_ptr< ::module_controller::SetServoAngleRequest> SetServoAngleRequestPtr;
typedef boost::shared_ptr< ::module_controller::SetServoAngleRequest const> SetServoAngleRequestConstPtr;


template <class ContainerAllocator>
struct SetServoAngleResponse_ : public ros::Message
{
  typedef SetServoAngleResponse_<ContainerAllocator> Type;

  SetServoAngleResponse_()
  : Success(0)
  {
  }

  SetServoAngleResponse_(const ContainerAllocator& _alloc)
  : Success(0)
  {
  }

  typedef int8_t _Success_type;
  int8_t Success;


private:
  static const char* __s_getDataType_() { return "module_controller/SetServoAngleResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1a8c06f1b4403f4bedd5ebdeca1af0dd"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "c5ba78eaaf56070109b47d88ff7a70ae"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 Success\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, Success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, Success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(Success);
    return size;
  }

  typedef boost::shared_ptr< ::module_controller::SetServoAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::module_controller::SetServoAngleResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SetServoAngleResponse
typedef  ::module_controller::SetServoAngleResponse_<std::allocator<void> > SetServoAngleResponse;

typedef boost::shared_ptr< ::module_controller::SetServoAngleResponse> SetServoAngleResponsePtr;
typedef boost::shared_ptr< ::module_controller::SetServoAngleResponse const> SetServoAngleResponseConstPtr;

struct SetServoAngle
{

typedef SetServoAngleRequest Request;
typedef SetServoAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetServoAngle
} // namespace module_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::SetServoAngleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5c52a171b7b8052392cf8b6496ff8559";
  }

  static const char* value(const  ::module_controller::SetServoAngleRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5c52a171b7b80523ULL;
  static const uint64_t static_value2 = 0x92cf8b6496ff8559ULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::SetServoAngleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoAngleRequest";
  }

  static const char* value(const  ::module_controller::SetServoAngleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::SetServoAngleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 ID\n\
float32 Angle\n\
\n\
";
  }

  static const char* value(const  ::module_controller::SetServoAngleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::SetServoAngleRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::module_controller::SetServoAngleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1a8c06f1b4403f4bedd5ebdeca1af0dd";
  }

  static const char* value(const  ::module_controller::SetServoAngleResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1a8c06f1b4403f4bULL;
  static const uint64_t static_value2 = 0xedd5ebdeca1af0ddULL;
};

template<class ContainerAllocator>
struct DataType< ::module_controller::SetServoAngleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoAngleResponse";
  }

  static const char* value(const  ::module_controller::SetServoAngleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::module_controller::SetServoAngleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 Success\n\
\n\
\n\
";
  }

  static const char* value(const  ::module_controller::SetServoAngleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::module_controller::SetServoAngleResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::SetServoAngleRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ID);
    stream.next(m.Angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetServoAngleRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::module_controller::SetServoAngleResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetServoAngleResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<module_controller::SetServoAngle> {
  static const char* value() 
  {
    return "c5ba78eaaf56070109b47d88ff7a70ae";
  }

  static const char* value(const module_controller::SetServoAngle&) { return value(); } 
};

template<>
struct DataType<module_controller::SetServoAngle> {
  static const char* value() 
  {
    return "module_controller/SetServoAngle";
  }

  static const char* value(const module_controller::SetServoAngle&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::SetServoAngleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5ba78eaaf56070109b47d88ff7a70ae";
  }

  static const char* value(const module_controller::SetServoAngleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::SetServoAngleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoAngle";
  }

  static const char* value(const module_controller::SetServoAngleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<module_controller::SetServoAngleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5ba78eaaf56070109b47d88ff7a70ae";
  }

  static const char* value(const module_controller::SetServoAngleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<module_controller::SetServoAngleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "module_controller/SetServoAngle";
  }

  static const char* value(const module_controller::SetServoAngleResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MODULE_CONTROLLER_SERVICE_SETSERVOANGLE_H

