(cl:defpackage module_controller-srv
  (:use )
  (:export
   "SETSERVOPOWER"
   "<SETSERVOPOWER-REQUEST>"
   "SETSERVOPOWER-REQUEST"
   "<SETSERVOPOWER-RESPONSE>"
   "SETSERVOPOWER-RESPONSE"
   "POLLSERVOANGLE"
   "<POLLSERVOANGLE-REQUEST>"
   "POLLSERVOANGLE-REQUEST"
   "<POLLSERVOANGLE-RESPONSE>"
   "POLLSERVOANGLE-RESPONSE"
  ))

