(cl:defpackage module_controller-srv
  (:use )
  (:export
   "SETSERVOPOWER"
   "<SETSERVOPOWER-REQUEST>"
   "SETSERVOPOWER-REQUEST"
   "<SETSERVOPOWER-RESPONSE>"
   "SETSERVOPOWER-RESPONSE"
   "GETSERVOANGLE"
   "<GETSERVOANGLE-REQUEST>"
   "GETSERVOANGLE-REQUEST"
   "<GETSERVOANGLE-RESPONSE>"
   "GETSERVOANGLE-RESPONSE"
  ))

