(cl:defpackage module_controller-srv
  (:use )
  (:export
   "SETSERVOPOWER"
   "<SETSERVOPOWER-REQUEST>"
   "SETSERVOPOWER-REQUEST"
   "<SETSERVOPOWER-RESPONSE>"
   "SETSERVOPOWER-RESPONSE"
   "SETSERVOANGLE"
   "<SETSERVOANGLE-REQUEST>"
   "SETSERVOANGLE-REQUEST"
   "<SETSERVOANGLE-RESPONSE>"
   "SETSERVOANGLE-RESPONSE"
   "GETSERVOPOWER"
   "<GETSERVOPOWER-REQUEST>"
   "GETSERVOPOWER-REQUEST"
   "<GETSERVOPOWER-RESPONSE>"
   "GETSERVOPOWER-RESPONSE"
   "GETSERVOANGLE"
   "<GETSERVOANGLE-REQUEST>"
   "GETSERVOANGLE-REQUEST"
   "<GETSERVOANGLE-RESPONSE>"
   "GETSERVOANGLE-RESPONSE"
  ))

